/* eslint-disable max-len */
// export const keys = ['Backquote', 'Digit1', 'Digit2', 'Digit3', 'Digit4',
//   'Digit5', 'Digit6', 'Digit7', 'Digit8', 'Digit9', 'Digit0', 'Minus', 'Equal',
//   'Backspace', 'Tab', 'KeyQ', 'KeyW', 'KeyE', 'KeyR', 'KeyT', 'KeyY', 'KeyU',
//   'KeyI', 'KeyO', 'KeyP', 'BracketLeft', 'BracketRight', 'IntlBackslash',
//   'CapsLock', 'KeyA', 'KeyS', 'KeyD', 'KeyF', 'KeyG', 'KeyH', 'KeyJ',
//   'KeyK', 'KeyL', 'Semicolon', 'Quote', 'Backslash', 'Enter', 'ShiftLeft',
//   'KeyZ', 'KeyX', 'KeyC', 'KeyV', 'KeyB', 'KeyN', 'KeyM', 'Comma', 'Period',
//   'Slash', 'ShiftRight', 'ControlLeft', 'AltLeft', 'MetaLeft', 'Space',
//   'MetaRight', 'AltRight', 'ArrowLeft', 'ArrowUp', 'ArrowDown', 'ArrowRight'];

export const keys = [
  {code: 'Backquote', default: '§', shift: '±', rus: '§', rusShift: '<'},
  {code: 'Digit1', default: '1', shift: '!', rus: '1', rusShift: '!'},
  {code: 'Digit2', default: '2', shift: '@', rus: '2', rusShift: '"'},
  {code: 'Digit3', default: '3', shift: '#', rus: '3', rusShift: '№'},
  {code: 'Digit4', default: '4', shift: '$', rus: '4', rusShift: '%'},
  {code: 'Digit5', default: '5', shift: '%', rus: '5', rusShift: ':'},
  {code: 'Digit6', default: '6', shift: '^', rus: '6', rusShift: ','},
  {code: 'Digit7', default: '7', shift: '&', rus: '7', rusShift: '.'},
  {code: 'Digit8', default: '8', shift: '*', rus: '8', rusShift: ';'},
  {code: 'Digit9', default: '9', shift: '(', rus: '9', rusShift: '('},
  {code: 'Digit0', default: '0', shift: ')', rus: '0', rusShift: ')'},
  {code: 'Minus', default: '-', shift: '_', rus: '-', rusShift: '_'},
  {code: 'Equal', default: '=', shift: '+', rus: '=', rusShift: '+'},
  {code: 'Backspace', default: 'Backspace', shift: 'Backspace', rus: 'Backspace', rusShift: 'Backspace'},
  {code: 'Tab', default: 'Tab', shift: 'Tab', rus: 'Tab', rusShift: 'Tab'},
  {code: 'KeyQ', default: 'q', shift: 'Q', rus: 'й', rusShift: 'Й'},
  {code: 'KeyW', default: 'w', shift: 'W', rus: 'ц', rusShift: 'Ц'},
  {code: 'KeyE', default: 'e', shift: 'E', rus: 'у', rusShift: 'У'},
  {code: 'KeyR', default: 'r', shift: 'R', rus: 'к', rusShift: 'К'},
  {code: 'KeyT', default: 't', shift: 'T', rus: 'е', rusShift: 'Е'},
  {code: 'KeyY', default: 'y', shift: 'Y', rus: 'н', rusShift: 'Н'},
  {code: 'KeyU', default: 'u', shift: 'U', rus: 'г', rusShift: 'Г'},
  {code: 'KeyI', default: 'i', shift: 'I', rus: 'ш', rusShift: 'Ш'},
  {code: 'KeyO', default: 'o', shift: 'O', rus: 'щ', rusShift: 'Щ'},
  {code: 'KeyP', default: 'p', shift: 'P', rus: 'з', rusShift: 'З'},
  {code: 'BracketLeft', default: '[', shift: '{', rus: 'х', rusShift: 'Х'},
  {code: 'BracketRight', default: ']', shift: '}', rus: 'ъ', rusShift: 'Ъ'},
  {code: 'IntlBackslash', default: '`', shift: '~', rus: ']', rusShift: '['},
  {code: 'CapsLock', default: 'CapsLock', shift: 'CapsLock', rus: 'CapsLock', rusShift: 'CapsLock'},
  {code: 'KeyA', default: 'a', shift: 'A', rus: 'ф', rusShift: 'Ф'},
  {code: 'KeyS', default: 's', shift: 'S', rus: 'ы', rusShift: 'Ы'},
  {code: 'KeyD', default: 'd', shift: 'D', rus: 'в', rusShift: 'В'},
  {code: 'KeyF', default: 'f', shift: 'F', rus: 'а', rusShift: 'А'},
  {code: 'KeyG', default: 'g', shift: 'G', rus: 'п', rusShift: 'П'},
  {code: 'KeyH', default: 'h', shift: 'H', rus: 'р', rusShift: 'Р'},
  {code: 'KeyJ', default: 'j', shift: 'J', rus: 'о', rusShift: 'О'},
  {code: 'KeyK', default: 'k', shift: 'K', rus: 'л', rusShift: 'Л'},
  {code: 'KeyL', default: 'l', shift: 'L', rus: 'д', rusShift: 'Д'},
  {code: 'Semicolon', default: ';', shift: ':', rus: 'ж', rusShift: 'Ж'},
  {code: 'Quote', default: '\'', shift: '"', rus: 'э', rusShift: 'Э'},
  {code: 'Backslash', default: '\\', shift: '|', rus: 'ё', rusShift: 'Ё'},
  {code: 'Enter', default: 'Enter', shift: 'Enter', rus: 'Enter', rusShift: 'Enter'},
  {code: 'ShiftLeft', default: 'Shift', shift: 'Shift', rus: 'Shift', rusShift: 'Shift'},
  {code: 'KeyZ', default: 'z', shift: 'Z', rus: 'я', rusShift: 'Я'},
  {code: 'KeyX', default: 'x', shift: 'X', rus: 'ч', rusShift: 'Ч'},
  {code: 'KeyC', default: 'c', shift: 'C', rus: 'с', rusShift: 'С'},
  {code: 'KeyV', default: 'v', shift: 'V', rus: 'м', rusShift: 'М'},
  {code: 'KeyB', default: 'b', shift: 'B', rus: 'и', rusShift: 'И'},
  {code: 'KeyN', default: 'n', shift: 'N', rus: 'т', rusShift: 'Т'},
  {code: 'KeyM', default: 'm', shift: 'M', rus: 'ь', rusShift: 'Ь'},
  {code: 'Comma', default: ',', shift: '<', rus: ',', rusShift: 'Б'},
  {code: 'Period', default: '.', shift: '>', rus: '.', rusShift: 'Ю'},
  {code: 'Slash', default: '/', shift: '?', rus: '/', rusShift: '?'},
  {code: 'ShiftRight', default: 'Shift', shift: 'Shift', rus: 'Shift', rusShift: 'Shift'},
  {code: 'ControlLeft', default: 'Control', shift: 'Control', rus: 'Control', rusShift: 'Control'},
  {code: 'AltLeft', default: 'Alt', shift: 'Alt', rus: 'Alt', rusShift: 'Alt'},
  {code: 'MetaLeft', default: 'Meta', shift: 'Meta', rus: 'Meta', rusShift: 'Meta'},
  {code: 'Space', default: 'Space', shift: 'Space', rus: 'Space', rusShift: 'Space'},
  {code: 'MetaRight', default: 'Meta', shift: 'Meta', rus: 'Meta', rusShift: 'Meta'},
  {code: 'AltRight', default: 'Alt', shift: 'Alt', rus: 'Alt', rusShift: 'Alt'},
  {code: 'ArrowLeft', default: 'ArrowLeft', shift: 'ArrowLeft', rus: 'ArrowLeft', rusShift: 'ArrowLeft'},
  {code: 'ArrowUp', default: 'ArrowUp', shift: 'ArrowUp', rus: 'ArrowUp', rusShift: 'ArrowUp'},
  {code: 'ArrowDown', default: 'ArrowDown', shift: 'ArrowDown', rus: 'ArrowDown', rusShift: 'ArrowDown'},
  {code: 'ArrowRight', default: 'ArrowRight', shift: 'ArrowRight', rus: 'ArrowRight', rusShift: 'ArrowRight'},
];
